export const QUIZ_CATEGORIES = [
  "None",
  "Other",
  "Job Interview",
  "Resume Building",
  "Public Speaking",
  "Business Etiquette",
  "Leadership",
  "Time Management",
  "Project Management",
  "Financial Literacy",
  "Productivity Tools",
  "Critical Thinking",
  "General Knowledge",
  "Geography",
  "World History",
  "Famous People",
  "Fun Facts",
  "Logic Puzzles",
  "Pop Culture",
  "Riddles",
  "Brain Teasers",
  "Mythology",
  "Biology",
  "Chemistry",
  "Physics",
  "Environmental Science",
  "Astronomy",
  "Arithmetic",
  "Algebra",
  "Geometry",
  "Calculus",
  "Statistics",
  "English Grammar",
  "Literature",
  "Writing Skills",
  "Vocabulary",
  "Spelling",
  "Art & Design",
  "Music Theory",
  "Civics",
  "Economics",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Political Science",
];
